### ISSUE TITLE
auto reformat code on commit & googlu

### ISSUE THREAD

**Issue by haakjunlee** [BungaeThunder/cakey-backend#43]
`./gradlew spotlessApply` 커밋시에 자동으로 실행되도록
googleJavaFormat().aosp() 스타일 점검

**Comment by Nanjangpan** [comment]
커밋시보다는 커밋에 이상이 있을때가 맞지 않을까?

**Comment by haakjunlee** [comment]
커밋 때마다 실행되긴 할테니까 정확히는 매 커밋 이전에가 맞겠네
