### ISSUE TITLE
Cors 설정

### ISSUE THREAD

**Issue by Nanjangpan** [BungaeThunder/cakey-backend#67]
Spring Boot에서 CORS(Cross-Origin Resource Sharing) 설정을 할 때는 다음과 같이 `@CrossOrigin` 어노테이션을 사용하거나, 전역 CORS 설정을 위해 `WebMvcConfigurer`를 사용할 수 있습니다.

1. **@CrossOrigin 어노테이션을 사용한 설정**

    `@CrossOrigin` 어노테이션을 사용하면 특정 컨트롤러 혹은 핸들러 메소드에 대해 CORS를 활성화 할 수 있습니다. 이 방법은 각각의 요청 경로에 대해 세밀하게 CORS를 설정할 수 있습니다.

    ```java
    @RestController
    @RequestMapping("/api")
    public class MyController {

        @CrossOrigin(origins = "http://localhost:3000")
        @GetMapping("/endpoint")
        public ResponseEntity<?> myHandler() {
            //...
        }
    }
    ```

    위 코드는 `http://localhost:3000`에서 오는 CORS 요청을 허용하도록 설정하였습니다.

2. **WebMvcConfigurer를 사용한 전역 설정**

    `WebMvcConfigurer`를 사용하면 전역적으로 CORS를 설정할 수 있습니다. 이 방법은 모든 요청 경로에 대해 동일한 CORS 정책을 적용하고자 할 때 유용합니다.

    ```java
    @Configuration
    public class MyConfig {

        @Bean
        public WebMvcConfigurer corsConfigurer() {
            return new WebMvcConfigurer() {
                @Override
                public void addCorsMappings(CorsRegistry registry) {
                    registry.addMapping("/**")
                            .allowedOrigins("http://localhost:3000")
                            .allowedMethods("GET","POST","PUT","DELETE")
                            .allowedHeaders("*")
                            .allowCredentials(true);
                }
            };
        }
    }
    ```

    위 코드는 모든 경로(`/**`)에 대해 `http://localhost:3000`에서 오는 CORS 요청을 허용하도록 설정하였습니다.

위 두 방법중 config로 하는 방법 채택

**Comment by Nanjangpan** [comment]
with chatGPT의 도움

**Comment by gyurinida** [comment]
CORS 참고
https://evan-moon.github.io/2020/05/21/about-cors/
